export const VUE_RULES = {
  'vue/comment-directive': ['error', { reportUnusedDisableDirectives: true }],
  'vue/no-reserved-component-names': [
    'error',
    {
      disallowVueBuiltInComponents: true,
      disallowVue3BuiltInComponents: true,
    },
  ],
  'vue/no-unused-vars': ['error', { ignorePattern: '^_' }],
  'vue/first-attribute-linebreak': [
    'error',
    {
      singleline: 'beside',
      multiline: 'below',
    },
  ],
  'vue/v-bind-style': ['error', 'shorthand', { sameNameShorthand: 'never' }],
  'vue/v-slot-style': [
    'error',
    {
      atComponent: 'shorthand',
      default: 'shorthand',
      named: 'shorthand',
    },
  ],
  'vue/block-order': [
    'error',
    { order: ['script', 'template', 'i18n', 'style[scoped]', 'style:not([scoped])'] },
  ],
  'vue/block-lang': [
    'error',
    {
      script: { lang: 'ts' },
      template: { lang: 'html', allowNoLang: true },
      i18n: { lang: 'yaml' },
      // style: { lang: 'scss' },
    },
  ],
  'vue/component-api-style': ['error', ['script-setup']],
  'vue/component-name-in-template-casing': [
    'error',
    'PascalCase',
    { registeredComponentsOnly: false },
  ],
  'vue/custom-event-name-casing': [
    'error',
    'kebab-case',
    { ignores: ['/^[a-z]+(?:-[a-z]+)*:[a-z]+(?:-[a-z]+)*$/u'] },
  ],
  'vue/define-emits-declaration': ['error', 'type-literal'],
  'vue/define-macros-order': [
    'error',
    {
      order: ['defineOptions', 'defineProps', 'defineEmits', 'defineModel', 'defineSlots'],
      defineExposeLast: true,
    },
  ],
  'vue/define-props-declaration': ['error', 'type-based'],
  'vue/define-props-destructuring': ['error', { destructure: 'always' }],
  'vue/html-button-has-type': ['error', { button: true, submit: false, reset: false }],
  'vue/html-comment-content-newline': 'error',
  'vue/html-comment-content-spacing': 'error',
  'vue/html-comment-indent': 'error',
  'vue/max-lines-per-block': [
    'warn',
    { script: 250, template: 150, style: 150, skipBlankLines: true },
  ],
  'vue/max-props': ['warn', { maxProps: 10 }],
  'vue/max-template-depth': ['warn', { maxDepth: 10 }],
  'vue/new-line-between-multi-line-property': 'error',
  'vue/next-tick-style': ['error', 'promise'],
  'vue/no-boolean-default': 'error',
  'vue/no-duplicate-class-names': 'error',
  'vue/no-empty-component-block': 'error',
  'vue/no-import-compiler-macros': 'error',
  'vue/no-literals-in-template': 'error',
  'vue/no-multiple-objects-in-class': 'error',
  'vue/no-negated-v-if-condition': 'error',
  'vue/no-ref-object-reactivity-loss': 'error',
  'vue/no-root-v-if': 'error',
  // 'vue/no-static-inline-styles': 'error', // TODO: consider enabling?
  'vue/no-template-target-blank': [
    'error',
    { allowReferrer: false, enforceDynamicLinks: 'always' },
  ],
  'vue/no-unused-emit-declarations': 'error',
  'vue/no-use-v-else-with-v-for': 'error',
  'vue/no-useless-mustaches': 'error',
  'vue/no-useless-v-bind': 'error',
  'vue/no-v-text': 'error',
  'vue/padding-line-between-blocks': 'error',
  'vue/prefer-prop-type-boolean-first': 'error',
  'vue/prefer-separate-static-class': 'error',
  'vue/prefer-single-event-payload': 'error',
  'vue/prefer-true-attribute-shorthand': 'error',
  'vue/prefer-use-template-ref': 'error',
  'vue/prefer-v-model': 'error',
  'vue/require-explicit-slots': 'error',
  'vue/require-macro-variable-name': 'error',
  'vue/require-typed-object-prop': 'error',
  'vue/require-typed-ref': 'error',
  'vue/slot-name-casing': ['error', 'kebab-case'],
  'vue/v-for-delimiter-style': 'error',
}
